apiVersion: skaffold/v1beta11
kind: Config
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
  - image: max-one.local:5001/jetson/ml-base
    custom:
      buildCommand: ./builder ml-base
      dependencies:
        paths:
          - src
        ignore:
          - .gitignore
