---

- name: "Check all hosts accessible"
  assert:
    that:
      - ansible_play_hosts == ansible_play_hosts_all

- name: "Install packages"
  apt:
    state: present
    update_cache: yes
    pkg:
      - xrdp
  register: packages

- name: "Reboot"
  reboot:
    reboot_timeout: 300
  when: packages.changed
  register: rebooted



