---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: jetson-l4t
  name: l4t-pvc
  labels:
    app: l4t
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
