---
- hosts: all

  connection: local

  tasks:
    - name: Add mappings to /etc/hosts
      tags:
        - hosts
      become: true
      blockinfile:
        path: /etc/hosts
        block: |
          {{ item.ip }} {{ item.name }}
        marker: "# {mark} jetson {{ item.name }}"
      with_items:
        - { name: nano-one.local, ip: 12.0.0.104 }
        - { name: xavier-one.local, ip: 12.0.0.105 }
        - { name: jupyter.local, ip: 12.0.0.208 }
        - { name: tensorflow-serving.local, ip: 12.0.0.209 }
        - { name: l4t.local, ip: 12.0.0.210 }
