---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: jetson-jupyter
  name: jupyter-pvc
  labels:
    app: jupyter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
