apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-query
  namespace: jetson-device-query
spec:
  template:
    spec:
      containers:
        - name: device-query
          imagePullPolicy: Always