---

- name: "Check all hosts accessible"
  assert:
    that:
      - ansible_play_hosts == ansible_play_hosts_all

- name: "Remove packages"
  apt:
    state: absent
    purge: yes
    pkg:
      - ubuntu-desktop
      - gdm3
  register: remove

- name: "Install packages"
  apt:
    state: present
    update_cache: yes
    pkg:
      - lxde
  register: install

- name: "Copy settings"
  copy:
    src: .Xresources
    dest: ~admin/.Xresources
  register: settings

- name: "Reboot"
  shell: sleep 5 && sync && shutdown -r now "Ansible Reboot"
  async: 1
  poll: 0
  ignore_errors: true
  when: remove.changed or install.changed or settings.changed
  register: rebooted

- name: "Wait for up"
  wait_for_connection:
    delay: 5
    connect_timeout: 5
    sleep: 1
    timeout: 240
  when: rebooted.changed

