---

- name: "Check all hosts accessible"
  assert:
    that:
      - ansible_play_hosts == ansible_play_hosts_all

- name: "Remove packages"
  apt:
    state: absent
    purge: yes
    pkg:
      - ubuntu-desktop
      - gdm3
  register: remove

- name: "Install packages"
  apt:
    state: present
    update_cache: yes
    pkg:
      - lxde
  register: install

- name: "Copy settings"
  copy:
    src: .Xresources
    dest: ~provision/.Xresources
  register: settings

- name: "Reboot"
  reboot:
    reboot_timeout: 300
  when: remove.changed or install.changed or settings.changed
  register: rebooted


