apiVersion: skaffold/v1beta11
kind: Config
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
    - image: max-one.local:5001/jetson/nano/tensorflow-serving
      custom:
        buildCommand: ../tools/builder tensorflow-serving
        dependencies:
          paths:
            - src
          ignore:
            - .gitignore
deploy:
  kustomize:
    path: kustomize/base
    flags:
      global:
        - "--namespace=jetson-tensorflow-serving"
profiles:
  - name: xavier
    activation:
      - env: JETSON_MODEL=xavier
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: max-one.local:5001/jetson/xavier/tensorflow-serving
      - op: replace
        path: /build/artifacts/0/custom/buildCommand
        value: ../tools/builder tensorflow-serving xavier max-one.local:5001/jetson/xavier/tensorflow-serving-base
      - op: replace
        path: /deploy/kustomize/path
        value: kustomize/overlays/xavier
  - name: docker-hub-parent
    patches:
      - op: replace
        path: /build/artifacts/0/custom/buildCommand
        value: ../tools/builder jupyter nano helmuthva/jetson-nano-ml-base
  - name: docker-hub
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: helmuthva/jetson-nano-tensorflow-serving
