apiVersion: skaffold/v1beta11
kind: Config
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
  - image: max-one.local:5001/jetson/tensorflow-serving
    custom:
      buildCommand: ../tools/builder tensorflow-serving
      dependencies:
        paths:
          - src
        ignore:
          - .gitignore
deploy:
  kustomize:
    path: kustomize/overlays/max
    flags:
      global:
        - "--namespace=jetson-tensorflow-serving"
profiles:
- name: max