---

- name: "Check all hosts accessible"
  assert:
    that:
      - ansible_play_hosts == ansible_play_hosts_all

- name: "Install packages"
  apt:
    state: present
    update_cache: yes
    pkg:
      - vnc4server
  register: packages

- name: "Create configuration directory"
  file:
    path: ~provision/.vnc
    state: directory
    owner: provision
    mode: "0700"

- name: "Set password"
  shell: "printf '{{ vnc.password }}\n{{ vnc.password }}\n\n' | vnc4passwd"

- name: "Copy configuration"
  copy:
    src: xstartup
    dest: ~provision/.vnc/xstartup
    owner: provision
    mode: "0700"

- name: "Start after boot"
  cron:
    user: "provision"
    name: "vncserver"
    special_time: reboot
    job: "/usr/bin/vncserver :1"
  register: cron

- name: "Reboot"
  reboot:
    reboot_timeout: 300
  when: cron.changed
  register: rebooted
