apiVersion: skaffold/v1beta11
kind: Config
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
  - image: max-one.local:5001/jetson/jupyter
    custom:
      buildCommand: ../tools/builder jupyter
      dependencies:
        paths:
          - src
        ignore:
          - .gitignore
deploy:
  kustomize:
    path: kustomize/base
    flags:
      global:
        - "--namespace=jetson-jupyter"
profiles:
- name: max
  patches:
    - op: replace
      path: /deploy/kustomize/path
      value: kustomize/overlays/max
- name: docker-hub-parent
  patches:
    - op: replace
      path: /build/artifacts/0/custom/buildCommand
      value: ../tools/builder jupyter helmuthva/jetson-ml-base
