apiVersion: skaffold/v1beta11
kind: Config
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
  - image: max-one.local:5001/jetson/jupyter
    custom:
      buildCommand: ./builder
      dependencies:
        paths:
          - src
        ignore:
          - .gitignore
deploy:
  kustomize:
    path: kustomize/overlays/max
    flags:
      global:
        - "--namespace=jetson-jupyter"
profiles:
- name: max