---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: jetson-tensorflow-serving
  name: tensorflow-serving-pvc
  labels:
    app: tensorflow-serving
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
