apiVersion: skaffold/v1beta11
kind: Config
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
  - image: max-one.local:5001/jetson/nano/l4t
    custom:
      buildCommand: ./builder.mac
      dependencies:
        paths:
          - src
        ignore:
          - .gitignore
deploy:
  kustomize:
    path: kustomize/base
    flags:
      global:
        - "--namespace=jetson-l4t"
profiles:
- name: xavier
  activation:
    - env: JETSON_MODEL=xavier
  patches:
    - op: replace
      path: /deploy/kustomize/path
      value: kustomize/overlays/xavier
