apiVersion: skaffold/v1beta11
kind: Config
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
  - image: max-one.local:5001/jetson/l4t
    custom:
      buildCommand: ./builder.mac
      dependencies:
        paths:
          - src
        ignore:
          - .gitignore
deploy:
  kustomize:
    path: kustomize/overlays/max
    flags:
      global:
        - "--namespace=jetson-l4t"
profiles:
- name: max