- name: "Check all hosts accessible"
  assert:
    that:
      - ansible_play_hosts == ansible_play_hosts_all

- name: "Ensure hostname set"
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname

- name: "Wait for any possibly running unattended upgrade to finish"
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

- name: "apt-get update"
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: "Install apt tools"
  apt:
    state: latest
    pkg:
      - aptitude
      - apt-transport-https
      - apt-utils

- name: "apt-get update"
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: "apt-get upgrade"
  apt:
    upgrade: full
  register: upgrade

- name: "Reboot"
  shell: sleep 5 && sync && shutdown -r now "Ansible Reboot"
  async: 1
  poll: 0
  ignore_errors: true
  when: hostname.changed or upgrade.changed
  register: rebooted

- name: "Wait for up"
  wait_for_connection:
    delay: 5
    connect_timeout: 5
    sleep: 1
    timeout: 240
  when: rebooted.changed

- name: "Install prerequisites"
  apt:
    state: latest
    pkg:
      - net-tools
      - dnsutils
      - sudo
      - sendmail-bin
      - python-setuptools
      - python-pip
      - ntp
      - telnet
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - ipvsadm
      - nano
      - nmap
      - htop
      - iotop

