- name: "Check all hosts accessible"
  assert:
    that:
      - ansible_play_hosts == ansible_play_hosts_all

- name: "Ensure hostname set"
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname

- name: "Wait for any possibly running unattended upgrade to finish"
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

- name: "apt-get update"
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: "Install apt tools"
  apt:
    state: latest
    pkg:
      - aptitude
      - apt-transport-https
      - apt-utils

- name: "apt-get update"
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: "apt-get upgrade"
  apt:
    upgrade: full
  register: upgrade

- name: "Reboot"
  reboot:
    reboot_timeout: 300
  when: hostname.changed or upgrade.changed
  register: rebooted

- name: "Install prerequisites"
  apt:
    state: latest
    pkg:
      - ca-certificates
      - curl
      - dnsutils
      - gnupg2
      - hdparm
      - htop
      - iotop
      - ipvsadm
      - nano
      - net-tools
      - nmap
      - ntp
      - python-pip
      - python-setuptools
      - sendmail-bin
      - software-properties-common
      - sudo
      - telnet

- name: "Install ctop"
  get_url:
    url: https://github.com/bcicen/ctop/releases/download/v0.7.2/ctop-0.7.2-linux-arm64
    dest: /usr/local/bin/ctop
    mode: '0755'