---

- name: "Set performance mode {{ nv.performance.mode }} and max frequencies"
  shell: |
    nvpmodel -m {{ nv.performance.mode }}
    /usr/bin/jetson_clocks
    /usr/bin/jetson_clocks --show
  register: performance

# - name: "Frequencies"
#   debug:
#     msg: "{{ performance.stdout }}"

- name: "Set max frequencies on boot"
  cron:
    name: "jetson_clocks"
    special_time: reboot
    job: "/usr/bin/jetson_clocks"
